# Generated by Django 2.2.1 on 2019-05-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booktagrel',
            table=None,
        ),
    ]
