# Generated by Django 2.2.1 on 2019-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created']},
        ),
    ]
